-- Team 2: Rachelle Burgos, Bahi Berk Gulay 
-- Attribution: ChatGPT 

CREATE TABLE COUNTRY (
  COUNTRY_NAME varchar(100),
  CODE varchar(3),
  COUNTRY_CAPITAL varchar(32),
  DESCRIPTION varchar(500),
  MEDIA_ID varchar(500),
  POPULATION unsigned int,
  MAIN_LANGUAGE varchar(32),
  CURRENCY varchar(32),
  TIMEZONE varchar(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE CITY (
  CITY_ID CHAR(36) PRIMARY KEY,
  COUNTRY_ID CHAR(36) REFERENCES COUNTRY_ID,
  CITY_NAME varchar(100),
  CITY_DESCRIPTION varchar(500),
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID,
  CITY_POPULATION unsigned int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE CITY_TRANSP (
  TRANSPORTATION_ID CHAR(36) PRIMARY KEY,
  CITY_ID CHAR(36) REFERENCES CITY_ID,
  TRANSPORTATION_DETAILS_ID CHAR(36) REFERENCES TRANSPORTATION_ID
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE TRANSP_MODE (
  TRANSPORTATION_DETAILS_ID CHAR(36) PRIMARY KEY,
  TRANSPORTATION_HOURS_ID CHAR(36) REFERENCES TRANSPORTATION_ID,
  TRANSPORTATION_TYPE enum,
  TRANSPORTATION_ACCESSIBILITY_ID CHAR(36) REFERENCES TRANSPORTATION_ID,
  TRANSPORTATION_MAX_PRICE decimal(10,2),
  TRANSPORTATION_MIN_PRICE decimal(10,2),
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE TRANSP_OPER_HRS (
  TRANSPORTATION_HOURS_ID CHAR(36) PRIMARY KEY,
  DAY_OF_WEEK enum,
  OPEN_TIME time,
  CLOSE_TIME time
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE TRANSP_ACCESS_INFO (
  TRANSPORTATION_ACCESSIBILITY_ID CHAR(36) PRIMARY KEY,
  TRANSPORTATION_DETAILS_ID CHAR(36) REFERENCES TRANSPORTATION_ID,
  WHEELCHAIR_ACCESSIBLE bool,
  HEARING_AID_COMPATIVILITY bool,
  VISUAL_AID_SUPPORT bool,
  STEP_FREE_ACCESS bool,
  STAFF_ASSISTANCE_AVAILABLE bool,
  ACCESSIBLE_BATHROOMS bool,
  SERVICE_ANIMAL_FRIENDLY bool,
  AUDIO_ANNOUNCEMENTS bool,
  RAMP_AVAILABILITY bool,
  PRIORITY_SEATING bool,
  ELEVATORS_AVAILABLE bool,
  ESCALATORS_AVAILABLE bool,
  OTHER_DETAILS varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIVITY (
  ACTIVITY_ID CHAR(36) PRIMARY KEY,
  CITY_ID CHAR(36) REFERENCES CITY_ID,
  ACTIVITY_DETAILS_ID CHAR(36) REFERENCES ACTIVITY_ID
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_REVIEW (
  ACTIVITY_REVIEW_ID CHAR(36) PRIMARY KEY,
  ACTIVITY_ID CHAR(36) REFERENCES ACTIVITY_ID,
  USER_ID CHAR(36) REFERENCES USER_ID,
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID,
  ACTIVITY_RATING tinyint,
  ACTIVITY_AMOUNT_SPENT decimal(10,2),
  ACTIVITY_REVIEW_TITLE varchar(100),
  ACTIVITY_REVIEW_BODY varchar(500),
  ACTIVITY_REVIEW_DATE datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_OPER_HRS (
  ACTIVITY_HOURS_ID CHAR(36) PRIMARY KEY,
  DAY_OF_WEEK enum PRIMARY KEY,
  OPEN_TIME time,
  CLOSE_TIME time
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_HISTORY (
  ACTIVITY_HISTORY_ID CHAR(36) PRIMARY KEY,
  USER_ID CHAR(36) REFERENCES USER_ID,
  ACTIVITY_ID CHAR(36) REFERENCES ACTIVITY_ID,
  ACTIVITY_ACTION_DATE datetime,
  ACTION_TYPE enum
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_DETAIL (
  ACTIVITY_ID CHAR(36) PRIMARY KEY,
  ACTIVITY_NAME varchar(100),
  ACTIVITY_HOURS_ID CHAR(36) REFERENCES ACTIVITY_ID,
  ACTIVITY_AVG_PRICE decimal(10,2),
  ACTIVITY_DESCRIPTION varchar(500),
  ACTIVITY_WEBSITE_URL varchar(500),
  ACTIVITY_PHONE varchar(20),
  ACTIVITY_AVG_RATING float,
  ACTIVITY_DATE_ADDED datetime,
  ACTIVITY_LAST_UPDATED datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACCOMMODATIONS (
  ACCOMMODATION_ID CHAR(36) PRIMARY KEY,
  CITY_ID CHAR(36) REFERENCES CITY_ID,
  ACCOMMODATIONS_DETAIL_ID CHAR(36) REFERENCES ACCOMMODATIONS_ID
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACCOMM_REVIEW (
  ACCOMMODATION_REVIEW_ID CHAR(36) PRIMARY KEY,
  ACCOMMODATION_ID CHAR(36) REFERENCES ACCOMMODATION_ID,
  USER_ID CHAR(36) REFERENCES USER_ID,
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID,
  ACCOMMODATION_RATING tinyint,
  ACCOMMODATION_AMOUNT_SPENT decimal(10,2),
  ACCOMMODATION_REVIEW_TITLE varchar(100),
  ACCOMMODATION_REVIEW_BODY varchar(500),
  ACCOMMODATION_REVIEW_DATE datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACCOM_HISTORY (
  ACCOMMODATION_HISTORY_ID CHAR(36) PRIMARY KEY,
  USER_ID CHAR(36) REFERENCES USER_ID,
  ACCOMMODATION_ID CHAR(36) REFERENCES ACCOMMODATION_ID,
  ACCOMMODATION_ACTION_DATE datetime,
  ACCOMMODATION_TYPE enum
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACCOM_DETAILS (
  ACCOMMODATION_ID CHAR(36) PRIMARY KEY,
  ACCOMMODATION_NAME varchar(100),
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID,
  ACCOMMODATION_AVG_PRICE decimal(10,2),
  ACCOMMODATION_DESCRIPTION varchar(500),
  ACCOMMODATION_WEBSITE_URL varchar(500),
  ACCOMMODATION_PHONE varchar(20),
  ACCOMMODATION_AVG_RATING tinyint,
  ACCOMMODATION_DATE_ADDED datetime,
  ACCOMMODATION_LAST_UPDATED datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT (
  EVENT_ID CHAR(36) PRIMARY KEY,
  CITY_ID CHAR(36) REFERENCES CITY_ID,
  EVENT_DETAIL_ID varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT_HISTORY (
  EVENT_HISTORY_ID CHAR(36) PRIMARY KEY,
  USER_ID CHAR(36) REFERENCES USER_ID,
  EVENT_ID CHAR(36) REFERENCES EVENT_ID,
  EVENT_ACTION_DATE datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT_DETAILS (
  EVENT_ID CHAR(36) PRIMARY KEY,
  EVENT_HOURS_ID CHAR(36) REFERENCES EVENT_ID,
  EVENT_NAME varchar(100),
  EVENT_AVG_PRICE decimal(10,2),
  EVENT_DESCRIPTION varchar(500),
  EVENT_WEBSITE_URL varchar(500),
  nan CHAR(36) REFERENCES MEDIA_ID,
  EVENT_PHONE varchar(20),
  EVENT_START_DATE date,
  EVENT_END_DATE date,
  EVENT_DATE_ADDED datetime,
  EVENT_LAST_UPDATED datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT_OPER_HRS (
  EVENT_HOURS_ID CHAR(36) PRIMARY KEY,
  DAY_OF_WEEK enum PRIMARY KEY,
  OPEN_TIME time,
  CLOSE_TIME time
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE USER (
  USER_ID CHAR(36) PRIMARY KEY,
  USER_EMAIL varchar(255),
  USER_DISPLAY_NAME varchar(50),
  USER_PASSWORD varchar(255),
  USER_FIRST_NAME varchar(50),
  USER_LAST_NAME varchar(50),
  USER_AGE tinyint,
  USER_TYPE enum,
  MEDIA_ID CHAR(36) REFERENCES MEDIA_ID,
  CREATED_AT datetime,
  LAST_LOGIN datetime,
  ACCOUNT_STATUS enum
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ITINERARY (
  ITINERARY_ID CHAR(36) PRIMARY KEY,
  USER_ID CHAR(36) REFERENCES USER_ID,
  ITINERARY_DATE_CREATED datetime,
  ITINERARY_LAST_UPDATED datetime,
  ITINERARY_NAME varchar(100),
  START_DATE date,
  END_DATE date,
  BUDGET decimal(10,2),
  PRIVACY_SETTING enum,
  STATUS enum,
  NOTES text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_ITINER_ITEM (
  ITEM_ID CHAR(36) PRIMARY KEY,
  ITINERARY_ID CHAR(36) REFERENCES ITINERARY_ID,
  ACTIVITY_ID CHAR(36) REFERENCES ACTIVITY_ID,
  TIME_PLANNED time,
  DATE_PLANNED date,
  DATE_ADDED datetime,
  DATE_MODIFIED datetime,
  STATUS enum,
  NOTES varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT_ITINER_ITEM (
  ITEM_ID CHAR(36) PRIMARY KEY,
  ITINERARY_ID CHAR(36) REFERENCES ITINERARY_ID,
  EVENT_ID CHAR(36) REFERENCES EVENT_ID,
  TIME_PLANNED time,
  DATE_PLANNED date,
  DATE_ADDED datetime,
  DATE_MODIFIED datetime,
  STATUS enum,
  NOTES varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE SHARED_ITINER (
  SHARED_ITINERARY_ID CHAR(36) PRIMARY KEY,
  ITINERARY_ID CHAR(36) REFERENCES ITINERARY_ID,
  SHARED_WITH_USER_ID CHAR(36) REFERENCES SHARED_ID,
  SHARED_ON_DATETIME datetime,
  ACCESS_LEVEL enum
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE BUCKET_LIST (
  BUCKET_LIST_ID CHAR(36) PRIMARY KEY,
  USER_ID CHAR(36) REFERENCES USER_ID,
  DATE_MODIFIED datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE ACTIV_BUCKET_LIST_ITEM (
  BUCKET_LIST_ITEM_ID CHAR(36) PRIMARY KEY,
  BUCKET_LIST_ID CHAR(36) REFERENCES BUCKET_ID,
  ACTIVITY_ID CHAR(36),
  DATE_ADDED datetime,
  DATE_COMPLETED datetime,
  PRIORITY enum,
  STATUS enum,
  NOTES varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE EVENT_BUCKET_LIST_ITEM (
  BUCKET_LIST_ITEM_ID CHAR(36) PRIMARY KEY,
  BUCKET_LIST_ID CHAR(36) REFERENCES BUCKET_ID,
  EVENT_ID CHAR(36),
  DATE_ADDED datetime,
  DATE_COMPLETED datetime,
  PRIORITY enum,
  STATUS enum,
  NOTES varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE MEDIA (
  MEDIA_ID CHAR(36) PRIMARY KEY,
  MEDIA_TYPE enum,
  MEDIA_URL varchar(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;